# Generated by Django 5.0.3 on 2024-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20201221_0029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="profile.jpg", upload_to="profile_pics"),
        ),
    ]
